In [1]:
import numpy as np

//Transformando uma lista em array

In [4]:
a = [1, 2, 3, 4, 5, 6, 7]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5, 6, 7])

//Visualizando os tipos de dados do array

In [5]:
arr.dtype

dtype('int64')

// Visualizando o formato do array

In [6]:
np.shape(arr)

(7,)

//Verificando o tamanho do array

In [7]:
np.size(arr)

7

In [9]:
a2 = [[2,355,6,88,9],[3,5,88,90,2]]

In [10]:
arr1 = np.array(a2)
arr1

array([[  2, 355,   6,  88,   9],
       [  3,   5,  88,  90,   2]])

// Array formado por duas linhas e cinco colunas

In [11]:
np.shape(arr1)

(2, 5)

// trazer o elemento que ocupa o lugar da coluna 1, linha 2

In [12]:
arr1[1,2]

88

//Trazer a linha zero do array

In [13]:
arr1[0, :]

array([  2, 355,   6,  88,   9])

// Trazer os elementos da linha 1, coluna 1 e 2

In [14]:
arr1[1, 1:3]

array([ 5, 88])

//Criando um array vazio de uma linha e seis colunas

In [15]:
np.empty(6, dtype='int32')

array([         0,          0,          0, 1071644672,          0,
       1072693248], dtype=int32)

//Criando um array do tipo 2 por 2

In [16]:
np.empty([2,2], dtype='int32')

array([[          0, -1073741824],
       [-2129100801,       31266]], dtype=int32)

//Criando arrays randomicos

In [17]:
np.random.randint(0,57, size=(3,3))


array([[ 5, 52, 27],
       [53, 42, 55],
       [30, 11, 36]])

In [19]:
test = np.random.randint(0,200, size=(50,5))
test

array([[ 50, 195,  17,  71,  52],
       [ 21,   1, 158, 112,  20],
       [116, 139, 165,  40, 174],
       [128, 128, 187,   8, 119],
       [198, 179, 180,  63,  96],
       [ 11,  41,  55, 196, 121],
       [190, 109,  22,  68, 136],
       [128, 106, 102, 178,  91],
       [ 68,  55,  46,  23,  41],
       [146,  20,   0, 189, 110],
       [ 90, 162,  93, 137, 164],
       [ 88,  21, 154, 191, 122],
       [ 52, 164,  54, 175,  81],
       [ 43,  21, 146, 175,  42],
       [135, 121, 112, 187, 109],
       [178,  22, 164,  80,  71],
       [170,   2,  27, 140,  36],
       [ 94, 171,  21,  45,  65],
       [174,  98,  76, 131, 170],
       [ 66,  97,  31, 157, 137],
       [187,  28, 196, 176,   3],
       [ 98, 149, 107,  84, 161],
       [184,  43, 120, 125, 153],
       [136, 107,  48,  79,  43],
       [ 33,  10,  88,  21, 163],
       [ 44,  41,  73,  99,  35],
       [197,  21,  88,  75,  71],
       [ 64, 130,  61,  53,  54],
       [177, 182, 183,  74,  50],
       [ 48,  

//Multiplicação escalar por um unico número

In [20]:
test1 = test * 2

In [21]:
test1

array([[100, 390,  34, 142, 104],
       [ 42,   2, 316, 224,  40],
       [232, 278, 330,  80, 348],
       [256, 256, 374,  16, 238],
       [396, 358, 360, 126, 192],
       [ 22,  82, 110, 392, 242],
       [380, 218,  44, 136, 272],
       [256, 212, 204, 356, 182],
       [136, 110,  92,  46,  82],
       [292,  40,   0, 378, 220],
       [180, 324, 186, 274, 328],
       [176,  42, 308, 382, 244],
       [104, 328, 108, 350, 162],
       [ 86,  42, 292, 350,  84],
       [270, 242, 224, 374, 218],
       [356,  44, 328, 160, 142],
       [340,   4,  54, 280,  72],
       [188, 342,  42,  90, 130],
       [348, 196, 152, 262, 340],
       [132, 194,  62, 314, 274],
       [374,  56, 392, 352,   6],
       [196, 298, 214, 168, 322],
       [368,  86, 240, 250, 306],
       [272, 214,  96, 158,  86],
       [ 66,  20, 176,  42, 326],
       [ 88,  82, 146, 198,  70],
       [394,  42, 176, 150, 142],
       [128, 260, 122, 106, 108],
       [354, 364, 366, 148, 100],
       [ 96,  

//Subtração de matrizes

In [22]:
sub = np.subtract(test1, test)
sub

array([[ 50, 195,  17,  71,  52],
       [ 21,   1, 158, 112,  20],
       [116, 139, 165,  40, 174],
       [128, 128, 187,   8, 119],
       [198, 179, 180,  63,  96],
       [ 11,  41,  55, 196, 121],
       [190, 109,  22,  68, 136],
       [128, 106, 102, 178,  91],
       [ 68,  55,  46,  23,  41],
       [146,  20,   0, 189, 110],
       [ 90, 162,  93, 137, 164],
       [ 88,  21, 154, 191, 122],
       [ 52, 164,  54, 175,  81],
       [ 43,  21, 146, 175,  42],
       [135, 121, 112, 187, 109],
       [178,  22, 164,  80,  71],
       [170,   2,  27, 140,  36],
       [ 94, 171,  21,  45,  65],
       [174,  98,  76, 131, 170],
       [ 66,  97,  31, 157, 137],
       [187,  28, 196, 176,   3],
       [ 98, 149, 107,  84, 161],
       [184,  43, 120, 125, 153],
       [136, 107,  48,  79,  43],
       [ 33,  10,  88,  21, 163],
       [ 44,  41,  73,  99,  35],
       [197,  21,  88,  75,  71],
       [ 64, 130,  61,  53,  54],
       [177, 182, 183,  74,  50],
       [ 48,  

In [23]:
test.mean()

103.584

//Moda

In [26]:


np.bincount(test.flatten()).argmax()


21

//Soma acumulada

In [27]:
test.cumsum(axis=1)

array([[ 50, 245, 262, 333, 385],
       [ 21,  22, 180, 292, 312],
       [116, 255, 420, 460, 634],
       [128, 256, 443, 451, 570],
       [198, 377, 557, 620, 716],
       [ 11,  52, 107, 303, 424],
       [190, 299, 321, 389, 525],
       [128, 234, 336, 514, 605],
       [ 68, 123, 169, 192, 233],
       [146, 166, 166, 355, 465],
       [ 90, 252, 345, 482, 646],
       [ 88, 109, 263, 454, 576],
       [ 52, 216, 270, 445, 526],
       [ 43,  64, 210, 385, 427],
       [135, 256, 368, 555, 664],
       [178, 200, 364, 444, 515],
       [170, 172, 199, 339, 375],
       [ 94, 265, 286, 331, 396],
       [174, 272, 348, 479, 649],
       [ 66, 163, 194, 351, 488],
       [187, 215, 411, 587, 590],
       [ 98, 247, 354, 438, 599],
       [184, 227, 347, 472, 625],
       [136, 243, 291, 370, 413],
       [ 33,  43, 131, 152, 315],
       [ 44,  85, 158, 257, 292],
       [197, 218, 306, 381, 452],
       [ 64, 194, 255, 308, 362],
       [177, 359, 542, 616, 666],
       [ 48,  

//Criando um array ordenado de 8 numeros

In [28]:
arr4 = np.arange(8)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

//Alterando a ordem dos numeros

In [29]:
arr5 = arr4.reshape(4,2)
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [30]:
arr6 = arr5.reshape(2,4)
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

//Matriz transposta

In [31]:
arr7 = arr6.T
arr7

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

//Concatenação de matrizes

In [33]:
arr8 = np.concatenate((arr5, arr7))
arr8

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

//Separação de arrays

In [34]:
np.split(arr7, 2)

[array([[0, 4],
        [1, 5]]),
 array([[2, 6],
        [3, 7]])]